name: student_connect
description: An app for students to manage tasks and get updates.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

# Project dependencies
dependencies:
  flutter:
    sdk: flutter
  
  # For making API calls to Open-Meteo
  http: ^1.2.1

  # For local storage of the task list
  shared_preferences: ^2.2.3

  # For opening the mail app from the contact form
  flutter_email_sender: ^6.0.3
  
  # For date and time formatting (if needed)
  intl: ^0.19.0
  
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# Flutter-specific configurations
flutter:
  uses-material-design: true